### PR TITLE
General enhancements

### PR DESCRIPTION
**Pull request by franklinWhaite**

### CODE REVIEW

**Review by celiajmd — APPROVED** [review]
Tested and LGTM

**Review by celiajmd — APPROVED** [review]

**Comment by afleisc** [comment]
maybe its just my configuration but I ran the rewrite example from the [README](https://github.com/GoogleCloudPlatform/bigquery-antipattern-recognition?tab=readme-ov-file#rewrite-using-ai-beta):

```
docker run \
    -v ~/.config:/root/.config \
    -i bigquery-antipattern-recognition \
    --query "select col1 from table1 where col2 like '%abc%' and col3=1" \
    --rewrite_sql \
    --processing_project_id <my-project>
```

and I got an error for rewrite 
Screenshot 2024-03-11 at 11 44 37 AM

**Comment by franklinWhaite** [comment]
@afleisc nice catch! just fixed the bug, feel free to test again

**Comment by afleisc** [comment]
LGTM
Screenshot 2024-03-12 at 10 39 44 AM

**Pull request merged**
